# Server Config
server:
  port: ${PORT:0}

# Application Config
spring:
  application:
    name: rede5por2
  cloud:
    config:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/torre
    username: postgres
    password: Postgres2022!
  jpa:
    hibernate:
      ddl-auto: update
      defer-datasource-initialization: true
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          show_sql: true
          format_sql: true
  # Zipkin
  # zipkin:
    # base-url: http://localhost:9411/
  # Flyway
  # flyway:
    # url: jdbc:postgresql://localhost:5432/postgres
    # user: postgres
    # password: Postgres2022!
  # RabbitMq Config
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: docker
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

# Eureka Config
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://torre-user:eedV365w@${eureka.instance.hostname}:8761/eureka/
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Message-Queue Config
mq:
  queues:
    torre-issuance: torre-issuance

# Management Config
management:
  endpoints:
    web:
      exposure:
        include: '*'
  # Sleuth
  tracing:
    sampling:
      probability: 1.0

#SprignDoc
springdoc:
  show-actuator: true 
  api-docs:
    path: rede5por2/v3/api-docs